name: ❓ Question
description: Ask a question about NiWrap.
title: "[Question]: "
labels: question
body:
  - type: input
    id: question
    attributes:
      label: Question
      description: "What is your question?"
      placeholder: "Enter your question"
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: "Provide any additional information or context about your question."
    validations:
      required: false