name: Python documentation

# This action works with pull requests and pushes
on:
  workflow_run:
    workflows: ["Styx compile"]
    types:
      - completed

jobs:
  styx:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
    
      - name: Install poetry
        run: pipx install poetry

      - uses: actions/setup-python@v5
        with:
          python-version-file: python/pyproject.toml
          cache: poetry

      - name: Install niwrap
        run: |
          poetry install --directory=python
          poetry add pdoc

      - name: Set up Git
        run: |
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            git config --global user.name "GitHub Actions"

      - name: Compile
        run: |
            poetry run pdoc niwrap -o docs_build -t python/docs/pdoc-theme --docformat google
            touch docs_build/.nojekyll
      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs_build
