name: Publish to PyPi

permissions:
  actions: write

on:
  push:
    tags:
    - '*'

jobs:
  pypi-release:
    name: PyPi Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          
      - name: Checkout styx
        uses: actions/checkout@v4
        with:
          repository: 'styx-api/styx'
          path: 'styx'
    
      - name: Install poetry
        run: pipx install poetry
        
      - uses: actions/setup-python@v5
        with:
          python-version-file: styx/pyproject.toml
          cache: poetry
          
      - name: Install styx
        run: poetry install --directory=styx
      
      - name: Compile
        run: |
          poetry --directory styx run python ../build.py

      - name: Publish to PyPi
        id: pypi_publish
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
          verbose: true
          packages-dir: dist/niwrap-python
