name: Validate & Spell-Check
on:
  push:
      branches:
      - main
      tags:
      - '*'
  pull_request:


jobs:
  check-schema:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate JSON
        uses: GrantBirki/json-yaml-validate@v3.2.1
        with:
          mode: warn
          base_dir: descriptors
          json_schema: schemas/descriptor.schema.json
          json_schema_version: draft-07
          ajv_strict_mode: false
          use_gitignore: false
          json_exclude_regex: ''
          
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v5

      - name: Install dependencies
        run: |
          pip install pytest

      - name: Run tests
        run: |
          pytest tests

